---
- name: Configure Azure Webservers
  hosts: azure
  become: yes
  vars:
    app_root: html_demo_site-main
    server_name: "{{ ansible_default_ipv4.address | default('localhost') }}"
  pre_tasks:
    - name: Install firewalld if not present
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open required ports
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ ports }}"

  roles:
    - role: webserver
      vars:
        app_root: html_demo_site-main
        # server_name: "{{ server_name }}"
