---
- name: Configure Azure Webservers
  hosts: azure
  become: true

  tasks:
  - name: Open ports 80 and 443
    ansible.builtin.firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 80/tcp
      - 443/tcp

  - name: Install Apache Web Server
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Start and enable httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
