---
- name: Configure Azure Webservers
  hosts: webservers
  become: true

  tasks:
    - name: Open ports 80 and 443
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 80/tcp
        - 443/tcp

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
