---
- name: Install nginx
  ansible.builtin.package:
    name: "{{ webserver }}"
    state: present

- name: Create website directories
  ansible.builtin.file:
    path: "/var/www/html/{{ item }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0770'
  loop:
    - www.companyplus.com
    - www.companypulsar.com

- name: Deploy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
