---
- name: Install nginx
  ansible.builtin.package:
    name: "{{ webserver }}"
    state: present

- name: Create website directories
  ansible.builtin.file:
    path: "/var/www/html/{{ item }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0770'
  loop:
    - www.companyplus.com
    - www.companypulsar.com

- name: Add index.html to each website
  ansible.builtin.copy:
    dest: "/var/www/html/{{ item }}/index.html"
    content: "<html><body><h1>Welcome to {{ item }}</h1></body></html>"
    owner: nginx
    group: nginx
    mode: '0644'
  loop:
    - www.companyplus.com
    - www.companypulsar.com

- name: Deploy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Deploy virtual host configuration
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
  loop:
    - www.companyplus.com
    - www.companypulsar.com
  notify: restart nginx

- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: present

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open ports using firewalld
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ ports }}"

- name: Check if companyplus directory exists
  stat:
    path: /var/www/html/www.companyplus.com
  register: dir_status

- name: Debug if directory exists
  debug:
    msg: "/var/www/html/www.companyplus.com exists."
  when: dir_status.stat.exists

- name: Debug if directory missing
  debug:
    msg: "ERROR: /var/www/html/www.companyplus.com does not exist!"
  when: not dir_status.stat.exists

- name: Deploy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
